#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend jacktravis-frontend
        bind *:80
        mode http
        default_backend jacktravis-backend

backend jacktravis-backend
	mode http
        balance roundrobin
        server 124466-web-01 34.201.161.126:80 check
        server 124466-web-02 52.91.178.14:80 check
"
sudo echo "$server_config" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
